#pragma once

#include <QString>
#include <QStringList>

// Procedurally synthesizes a small set of soothing built-in sounds as 16-bit
// PCM WAV files. No audio assets are shipped -- everything is generated by pure
// math on first run, so nothing is copyrighted.
class SoundGenerator {
public:
    // Names (with .wav) of the built-in sounds this generator produces.
    static QStringList builtinNames();

    // Ensure every built-in exists in Config::soundsDir(). Missing ones are
    // (re)generated. Cheap and idempotent -- safe to call every launch.
    static void ensureBuiltins();
};
